name: Build Applications

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  build_applications:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2016]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pyinstaller
      run: pip install git+https://github.com/pyinstaller/pyinstaller
    - name: Install glue
      run: pip install glueviz PyQt5==5.11.3
    - name: Run pyinstaller
      run: pyinstaller glue_app.spec
    - name: Prepare MacOS X application and make dmg
      if: matrix.os == 'macos-10.15'
      run: osx/make_dmg.sh
    - name: Install awscli
      run: pip install awscli
    - name: Upload to S3
      shell: bash
      run: aws s3 cp * s3://glue-installers-exp/
      working-directory: dist
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
